### ISSUE TITLE
AppConfig default values fail to remove

### ISSUE THREAD

**Issue by gudlyf** [rebuy-de/aws-nuke#1077]
May need to default ignoring these. Can confirm AppConfig was never used or accessed with this account, yet it tries to remove these and fails:

```
us-east-1 - AppConfigDeploymentStrategy - [ID: "AppConfig.AllAtOnce", Name: "AppConfig.AllAtOnce"] - failed
us-east-1 - AppConfigDeploymentStrategy - [ID: "AppConfig.Linear50PercentEvery30Seconds", Name: "AppConfig.Linear50PercentEvery30Seconds"] - failed
us-east-1 - AppConfigDeploymentStrategy - [ID: "AppConfig.Canary10Percent20Minutes", Name: "AppConfig.Canary10Percent20Minutes"] - failed
us-east-1 - AppConfigDeploymentStrategy - [ID: "AppConfig.Linear20PercentEvery6Minutes", Name: "AppConfig.Linear20PercentEvery6Minutes"] - failed
```

**Comment by fernandoataoldotcom** [comment]
I'm running into this as well - I haven't contributed to this project before, although am a fan.

I started some changes that I think should work, based on other filtering implemented, but am threadding your comment rather than opening a PR in case I got something obvious wrong:
https://github.com/rebuy-de/aws-nuke/compare/main...fernandoataoldotcom:aws-nuke:fix/filter-default-app-config-deployment-strategies?expand=1

**Comment by enigmango** [comment]
I'm seeing this too, but we're want to use this latest version because it supports MGN resources. As a workaround for now, we've added `AppConfigDeploymentStrategy` to the excluded resource types in the config file. Example:

```yaml
resource-types:
  excludes:
    - AppConfigDeploymentStrategy
```
