### ISSUE TITLE
Lack of pagination support for multiple list functions

### ISSUE THREAD

**Issue by josesolisrosales** [rebuy-de/aws-nuke#1159]
Self-explanatory. 
So far, I found this is happening in `iam-user-policy.go` and `iam-list-user-group-attachments.go` in the `ListIAMUserPolicies` and `ListIAMUserGroupAttachments` functions respectively

This results in only some of the objects getting listed. Since these functions build a resource list based on the Users listed, this list is incomplete. Since pagination is properly implemented in `iam-users.go`, user deletion can fail if the attachment was not generated for that User.

#1158

**Comment by ekristen** [comment]
Please feel free to open a PR over on the fork at https://github.com/ekristen/aws-nuke, otherwise, I have this as part of my backlog.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
