### ISSUE TITLE
Unstable branch?

### ISSUE THREAD

**Issue by rburchill** [rebuy-de/aws-nuke#1187]
Considering there are 53 open PRs as of writing this, is it worth considering an unstable branch where things get merged quicker?

I can't see too many downsides as long as people are warned that the branch is unstable. Open to other ideas.

**Comment by mdirkse** [comment]
Agreed. Also, looking at the commits and releases, it seems that work on this repo has kind of stalled since August of last year. Perhaps the committers could use some help with the project?

**Comment by svenwltr** [comment]
Hello! We do have indeed not much time for this project. Also, it does not look like this will change soon.

We could the `main` branch consider unstable, but PRs still need to get reviewed. Once they get merged nobody would review them anymore.

Yes we could use some help with the project, but we do not have a clear idea how to get trustworthy contributors. In the past some people already offered help, but stopped support again quite soon, making the whole topic even more complicated.

**Comment by rburchill** [comment]
Yeah, I get it. You don't want the quality to drop. In an ideal world PRs that add support for new resources would be merged quickly and anyone willing and capable of building aws-nuke themselves could take advantage of the new resource support. I realise I am only really thinking about the happy path here. Perhaps more automated testing could help?

Also, maybe you should speak with @ekristen, since he seems to be maintaining a version of aws-nuke that merges PRs quicker.

**Comment by ekristen** [comment]
I've avoided commenting on this issue as I'm biased, but since I've been pinged directly now here's my feedback.

First what Sven and the rebuy team have built here is great, and I can't thank them enough for it. However it's clear they don't have the time or cycles to routinely contribute to the project.

As such I'm letting anyone who reads this, that there's a fork that's maintained more frequently now [ekristen/aws-nuke@v3](https://github.com/ekristen/aws-nuke).

**Important:** I kept all git history and all attribution to where the source originally came from. It is important to me that others know this, without the hard work of those that came before, the work I've done recently would not have been possible.

### History / Backstory

Several years ago I asked to make some changes (#714, #715) these were just the initial changes I wanted to make to test the waters. I then asked about the state of this project (#717) and what it would take to allow others to help, while generally open to the idea, it was made clear that it wouldn't be quick to make that happen and given how infrequently the team works on it, I dropped the idea, as it was clear it would take way longer than for me to just fork the project.

I officially forked [ekristen/aws-nuke@v3](https://github.com/ekristen/aws-nuke) around December of 2021 due to the above. Last December (2023), I set out and rewrote the whole thing to setup for possible features like dependencies, upgrading of AWS SDK version, and may features users have been asking for for a long while like global filters, bypass alias checks, run against all enabled regions, better tests and documentation.

I took the entire core library and broke it out into it's [own library](https://github.com/ekristen/libnuke) and it has 95%+ test coverage! All new resources are getting unit tests. Check out the [documentation for ekristen/aws-nuke](https://ekristen.github.io/aws-nuke/) for more information, reply here or email me. Happy to talk more. I've also built a tool for azure [azure-nuke](https://github.com/ekristen/azure-nuke) and I'm in the process of starting one for GCP as well. 

### Thanks

To the rebuy team, thanks for the tool and all the hard work you've done. Thanks for making this tool open source. If you want to talk about leveraging what I've done hit me up, if you don't no worries. I hope nothing but the best for you all and hope you find time to work on the tool.

**Comment by Petersoj** [comment]
@ekristen fantastic work on your fork! Thank you for picking things up. Perhaps @svenwltr can add a reference to your fork in the README of this repo for future users.

**Comment by svenwltr** [comment]
Thanks for your response and for keeping working on this despite our low reponsiveness, @ekristen! 

I can only motivate everyone who is interested in push aws-nuke forward to look into ekristen/aws-nuke@v3 and give it a star. I am happy to pass the torch, when it gets enough traction.

Meanwhile I am pinning this issue.

**Comment by npellegrin** [comment]
It saddens me to see projects being forked when the only reason is a lack of maintainers. After several weeks without my latest contribution being merged, I decided to [upload it to the ekristen/aws-nuke repository](https://github.com/ekristen/aws-nuke/issues/157), which merged it later that day.

I'm not a big contributor, but I regularly need new resources to delete and I'm always happy to be able to help myself by contributing to this kind of project and get the functionality I'm missing. I understand the workload involved in following up such a project, and personally I wouldn't be able to do it on a regular basis. I'm very grateful to the rebuy.de team for all their hard work in creating this tool.

A page is slowly being turned. I'll probably continue to propose changes at both rebuy.de/aws-nuke and ekristen/aws-nuke for a while, but the faster the integration at one, the less inclined I'll be to backport my changes to the other 😟

**Comment by ekristen** [comment]
My fork is now the actively maintained fork for aws-nuke. 

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
