### ISSUE TITLE
[Performance] Global Items are inspected in every region

### ISSUE THREAD

**Issue by tomvachon** [rebuy-de/aws-nuke#123]
For services which we know are global (e.g. IAM), it should only be inspected in one region and deleted in one region (or three if you want to be exact).  

For normal usage, it should be deleted off the first region in the list.  We should encourage users to put their highest usage region at the top for obvious reasons.

Scenario 2, would include GovCloud, so we should ensure that if someone runs this against GovCloud, that region is also interrogated for IAM (or other "global" services).

Like Scenario 2, and CN region should also be investigated separately in addition to the first "public" region in their list

**Comment by svenwltr** [comment]
Maybe we should just introduce a virtual region which is called `global`?

**Comment by bjoernhaeuser** [comment]
I like this idea. In the end stuff like s3 buckets are "global" - thats even the term aws is using.

**Comment by tomvachon** [comment]
It has to be ensured that if they also put in a GovCloud or CN region, those are checked as well as global

**Comment by svenwltr** [comment]
I actually have no idea how the GovCloud and CN work. According [to docs](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#pkg-constants) these are called partitions and it should be possible to do this.

I am not sure whether we can support other partitions at all, since we are not able to test these. Also adding support to them should be in a separate issue.

**Comment by tomvachon** [comment]
Fair enough
