### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by FernandoMiguel** [rebuy-de/aws-nuke#125]
would it be possible to make a brew formula, so it's easy to auto update?

**Comment by svenwltr** [comment]
I don't know anything about brew, since I don't have a Mac. @rebuy-de/prp-aws-nuke Anyone know how to do that and how hard this is?

**Comment by bjoernhaeuser** [comment]
I am not sure brew would accept this right now. They actually require a website. Also they prefer that not the authors themselves contribute the formulae, but someone else.

@FernandoMiguel do you want to contribute the formulae in this case? :)

**Comment by FernandoMiguel** [comment]
not particularly versed in ruby

**Comment by tomvachon** [comment]
I am, Let me see what I can do

**Comment by tomvachon** [comment]
@svenwltr Can we make a github.io page for this?

**Comment by FernandoMiguel** [comment]
did this ever got any traction @tomvachon ?

**Comment by PatMyron** [comment]
Wouldn't https://github.com/rebuy-de/aws-nuke suffice for the homepage?

https://docs.brew.sh/Acceptable-Formulae

**Comment by svenwltr** [comment]
Yes, the GitHub repo might count as a homepage, but there is still the problem that they do not want self-submitted stuff:

> We frown on authors submitting their own work unless it is very popular.

See https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

**Comment by bodnarbm** [comment]
@svenwltr The formula has been accepted and `aws-nuke` should now be available via homebrew on linux and macos platforms.

When the next aws-nuke version releases, I'll try to update the formula with that version release, and if it works with the simplified process for formulae to update, I'll see if I can also add it to the auto-bump list for homebrew so that each version update gets pushed out via homebrew too.
