### ISSUE TITLE
FSx FileSystem Deletion Fails When SVM Has Non-Root Attached Volumes

### ISSUE THREAD

**Issue by hidday** [rebuy-de/aws-nuke#1250]
Deleting FSx filesystems is failing when trying to delete an SVM with non-root attached volumes. 
This issue needs to be addressed to ensure a more reliable cleanup process.

Linked PR: 
[PR #1249](https://github.com/rebuy-de/aws-nuke/pull/1249)[Enhance FSx FileSystem Deletion with Retry Logic and SVM Handling](https://github.com/rebuy-de/aws-nuke/pull/1249)

**Comment by ekristen** [comment]
Closing since there is a PR. PR will be reviewed for inclusion in the fork, if it's unable to be I will comment on the PR.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
