### ISSUE TITLE
Reparent AWS-Nuke Project

### ISSUE THREAD

**Issue by tomvachon** [rebuy-de/aws-nuke#127]
@svenwltr and @bethge, this project has been getting quite a bit of traction lately.  It might be time to reparent it up to its own Org in Github.  I'd be happy to help out on the project admin side, but I doubt you want to give me access while its under the Rebuy Org.

Thoughts?

**Comment by FernandoMiguel** [comment]
Repos can have mantainers that are outside the org, and even be transferred ownership

**Comment by tomvachon** [comment]
@FernandoMiguel Yes, but it might be a political issue

**Comment by bethge** [comment]
We have been discussing this issue quite extensively internally.

We are very happy to have build something others find useful as well and greatly appreciate the numerous additions to the list of supported resources!

Yet, for the time being, we believe it is more advantageous to the project to remain in the rebuy-de organization. It allows us at reBuy to more easily allocate time to the project since it gives our company a bit of exposure.
Additionally, as long as it is part of the rebuy-de organization it will also be maintained by us at reBuy. This reduces the chances of the project being abandoned.

Our goal is to respond within 2-3 days to bugs and within a week to feature additions.

We will keep this issue open and given more community feedback will happily reconsider our stance on the matter.

**Comment by ekristen** [comment]
Deprecated in favor of https://github.com/ekristen/aws-nuke, I do have plans to setup a separate org when we get enough contributors for all 3 nuke projects and the library that now powers them.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
