### ISSUE TITLE
Question: Only nuke Resources with certain Tag?

### ISSUE THREAD

**Issue by leflamm** [rebuy-de/aws-nuke#218]
Hi,

Can I configure `awsnuke` so that it only nukes resources that have been tagged with <special_key>:<special_value> ?

Cheers, Christian.

**Comment by nisabek** [comment]
Hi,

For the configuration file, what about having the tag key/value in the same style as most of the aws cli filter queries. e.g. to filter all Cloudformation resources who's tag "owner" == "myteam"

`    CloudFormation:
        - property: "tag:owner"
          value: "myteam"
`

**Comment by svenwltr** [comment]
Hmm ... do you actually want to set a filter per resource type, or globally? I though it is about the latter one.

**Comment by svenwltr** [comment]
Ok, I guess we have to implement both here. The actual work lies in adding it to each resource in `resources/` anyway. We just have to keep this in mind when designing the API for the resources.

So we need:
* A per-resource filter that marks resources to *exclude*.
* A per-account filter, that marks resources to *include*.

**Comment by nisabek** [comment]
Do we have to change anything in the filters (code-wise)? or do you think can we keep things as-is, but 1) implement the ResourcePropertyGetter for all 
2) include the tags in the properties ( e.g. for all tags: Set("tagKey", tagValue))

**Comment by svenwltr** [comment]
I would suggest to start with the per-resource filters and not touch the filter code, yet.

Yes we should utilize the `Properties` type for this, but it should be sophisticated enough so we can easily get all tags for any resource (ie something like `Properties.GetTags() map[string]string`). Since the AWS SDK does not provide a unified interface for tags, I suggest to add something like `Properties.SetTag(key string, value string)` and use it in the actual resources. The `SetTag` function could properly add it to the underlying map.

I think the most important thing is to design it in a way, where the code in the actual resources requires as less code as possible.

**Comment by nisabek** [comment]
https://github.com/rebuy-de/aws-nuke/pull/237

**Comment by fredshino** [comment]
Can I add something similar to this request?

_A per-account filter, that marks resources with a certain tag to exclude._

Basically instead of filtering tagged resources per resource-type like this:
`filters:
      LambdaFunction:
      - property: "tag:ManagedResource"
        value: "True"
      S3Bucket:
      - property: "tag:ManagedResource"
        value: "True"
      CloudFormationStack:
      - property: "tag:ManagedResource"
        value: "True"`

I want to be able to do this:
`filters:
      AllResources:
      - property: "tag:ManagedResource"
        value: "True"`

**Comment by korenyoni** [comment]
While the feature mentioned by @fredshino does not exist, and it would be nice if it did, in the event that you want to delete all resources that have a specific tag, you can write a script to generate a (very long) aws-nuke config that applies this filter on all resource types (except those that [do not support custom properties](https://github.com/rebuy-de/aws-nuke/blob/f7337e5c069b424605f80eac24f117a6394fb410/cmd/queue.go#L69-L75)):

```bash
#!/bin/sh

cat <<-EOT
regions:
  - us-east-1
  - global

account-blocklist:
  - "123456789012" # production

resource-types:
  excludes:
  # The following resources cannot be filtered by tags (aws-nuke error: "does not support custom properties")
  - IAMSAMLProvider
  - ECRRepository
  - ElasticacheSubnetGroup
  - CloudWatchEventsRule
  - SQSQueue
  - ElasticacheCacheCluster
  - ElasticacheReplicationGroup
  - NetpuneSnapshot
  - NeptuneInstance
  - NeptuneCluster
  - LifecycleHook
  - CloudWatchEventsTarget
  - MQBroker
  # The following resources are unvailable due to deprecated APIs or other issues:
  - FMSPolicy
  - MachineLearningMLModel
  - FMSNotificationChannel
  - MachineLearningBranchPrediction
  - MachineLearningEvaluation
  - MachineLearningDataSource

accounts:
  "000000000000": # the account in question
    filters:
EOT
for resource_type in $(aws-nuke resource-types); 
do  
    cat <<-EOT
      $resource_type:
      - property: "tag:Environment"
        value: "foo"
        invert: true
EOT
done
```

Mind you because of the inability to filter some resources based on tags, the following resource types would be left alone and not nuked:

```
  - IAMSAMLProvider
  - ECRRepository
  - ElasticacheSubnetGroup
  - CloudWatchEventsRuleƒ
  - SQSQueue
  - ElasticacheCacheCluster
  - ElasticacheReplicationGroup
  - NetpuneSnapshot
  - NeptuneInstance
  - NeptuneCluster
  - LifecycleHook
  - CloudWatchEventsTarget
  - MQBroker
```

Probably, the ones of interest to delete (would probably accrue costs or are more likely to be related to an environment you want to delete) are:
```
  - ECRRepository
  - ElasticacheSubnetGroup
  - ElasticacheCacheCluster
  - ElasticacheReplicationGroup
  - MQBroker
  - SQSQueue
```

**Comment by ekristen** [comment]
Tracking a potential feature idea here https://github.com/ekristen/aws-nuke/issues/327
