### ISSUE TITLE
S3Bucket nuking doesn't function if the bucket is not empty

### ISSUE THREAD

**Issue by scottybrisbane** [rebuy-de/aws-nuke#263]
I have been contemplating submitting a PR to modify the logic for S3Bucket nuking to go through and delete all the objects in a bucket before trying to remove the bucket. This is due to the fact that nuking a non-empty bucket doesn't work, and in my opinion it should as the tool is aimed at being a very destructive cleanup tool.

We have performance issues (including OOM) with nuking S3Objects, due to the fact that it lists every single object in all buckets and stores this in memory (see #262). Ideally, we don't actually need to nuke S3Objects since we should be able to just nuke the entire bucket. Due to the above issue, however, we need to nuke S3Objects as well as S3Buckets.

Would the maintainers be open to such a PR?

**Comment by svenwltr** [comment]
I guess that would be fine. I first had doubts, because there might be people which want to protect some objects in S3, but this does not really makes sense, since the user would need to exclude the Bucket anyway.

@rebuy-de/prp-aws-nuke Opinions on that?

**Comment by bjoernhaeuser** [comment]
@scottybrisbane Just one thing I want to mention. We stopped nuking the actual buckets, because AWS takes ages to make the name available again (easily up to 24 hours). That knowing terraforming your account (and then nuking it) really does not work. 

That being said, I would be open for such a PR. ;)
