### ISSUE TITLE
Add support for "report only" mode

### ISSUE THREAD

**Issue by gebailey** [rebuy-de/aws-nuke#369]
Would be nice if there was some way to use aws-nuke's ability to inventory resources, even on a production account.

```
aws-nuke --report --access-key-id $AWS_ACCESS_KEY_ID --secret-access-key $AWS_SECRET_ACCESS_KEY --config prod-env.yaml
```

Above could dump out detected resources, and because it's only a report, the normal checks for account alias, no "prod" in the alias, etc., could be bypassed.

**Comment by svenwltr** [comment]
Hello @gebailey,

while is completely understand the desire for such a feature, I think it is a quite dangerous one. Of course it is possible to safely implement it, but it requires rather much work, because if needs proper testing.

Additionally, it is possible to achieve this with the Tag Editor. See https://stackoverflow.com/a/51450680/393157.
