### ISSUE TITLE
cannot nuke without iam:ListAccountAliases

### ISSUE THREAD

**Issue by bryfry** [rebuy-de/aws-nuke#382]
I'd like to be able to force (via config or flags) to skip the iam:ListAccountAliases.  I have accounts where this IAM role isn't available but I don't see a way past this check.  Thanks for any info!

**Comment by svenwltr** [comment]
Hello @bryfry,

I am very sorry for the late response. Somehow I missed this ticket.

The use of `iam:ListAccountAliases` is required as part of a safety guard against accidentally destroying a production account. Due to the destructive nature of this tool, I really do not want to add any workarounds or force flags for this.

Also, not having permissions to do `iam:ListAccountAliases` makes me wonder what kind of environment you want to execute *aws-nuke*?
