### ISSUE TITLE
Push to Docker registry

### ISSUE THREAD

**Issue by sc250024** [rebuy-de/aws-nuke#408]
## Description

It seems that even though a `Dockerfile` exists for this project, and the Docker image is built (https://github.com/rebuy-de/aws-nuke/blob/master/.travis.yml#L9), it's not actually pushed to any Docker registry.

The project should be pushed to a Docker registry. Someone already attempted this from a fork of the project (https://hub.docker.com/r/onfido/aws-nuke/), but that Docker image is more than a year old.

## Expected Behavior

The `aws-nuke` project should push to a Docker registry.

## Actual Behavior

Currently the Docker image is built, but the resulting image is not pushed anywhere.

## Specifications

I can make the resulting PR, but I would need someone from reBuy reCommerce GmbH to actually create a DockerHub, or a Quay registry for the organization, if it doesn't already.

**Comment by der-eismann** [comment]
Actually `aws-nuke` is regularly built and pushed to a Docker registry. As we mention in the Docker section of our [Readme](https://github.com/rebuy-de/aws-nuke#docker) the repo is located at [quay.io/rebuy/aws-nuke](https://quay.io/repository/rebuy/aws-nuke). Is this okay for you or would you expect something else?

It may be confusing because the travis job is really only building and not pushing because quay is building the image itself.

**Comment by sc250024** [comment]
Ah sorry @der-eismann I should RTFM next time 😄 Thank you!

**Comment by der-eismann** [comment]
No problem, happens to all of us :smile:
