### ISSUE TITLE
Unable to delete EBS snapshot when Fast Snapshot Restore (FSR) is enabled

### ISSUE THREAD

**Issue by npellegrin** [rebuy-de/aws-nuke#453]
I had an issue with deleting an EBS snapshot when the _Fast Snapshot Restore_ feature is enabled on it.

The error message is: `InvalidSnapshot.InUse: The snapshot snap-00e4b125ff8f080bf is currently enabled for fast restores in eu-west-1b. Fast snapshot restores must be disabled within all Availability Zones before the snapshot may be deleted.`

The Fast Snapshot Restore is a new AWS feature (Nov. 2019)
About the feature: https://aws.amazon.com/blogs/aws/new-amazon-ebs-fast-snapshot-restore-fsr/

**Comment by ekristen** [comment]
Closing due to age, if this is still a desired feature please open an issue at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
