### ISSUE TITLE
feature - ignore explicit deny (AWS SCP)

### ISSUE THREAD

**Issue by jack1902** [rebuy-de/aws-nuke#495]
### Description

When running `aws-nuke` within an account which has SCP' (Service Control Policies). It would be great to tell `aws-nuke` to ignore errors such as:

```
AccessDeniedException: User: arn:aws:sts::1234:assumed-role/admin/1234 is not authorized to perform: servicecatalog:ListPortfolios on resource: arn:aws:servicecatalog:REGION:123:*/* with an explicit deny
```

These errors really clutter the output, and are ones that i am happy to ignore, as the SCPs in use prevent anything in a given account creating a resource for that service.

Example:
- Service X is disabled
- Checking Service X is pointless, as it is disabled therefor no resources will exist for it

I know there is an alternative to use the below on the SCP, but wondering what the direction of this tool is:

```json
"Condition": {
  "StringNotLike": {
    "aws:PrincipalARN":"arn:aws:iam::*:role/AdminRole"
  }
}
```

## Desired change

The ability to pass a flag to "ignore" explicit denies. (a flag `--ignore-explicit-denies` because this wouldn't be a desirable default IMHO)

**Comment by svenwltr** [comment]
Hello @jack1902,

on a first thought I think this is not straightforward to implement, because the error code `AccessDeniedException` is not distinguishable from the error code that gets returned, if a user is using wrong credentials. Accidentally swallowing this error would make debugging for new users very hard.

Therefore we could do some regex to identify the error and hope there are no false negatives. So having the proposed flag would be helpful `--ignore-explicit-denies`.

Are you willing to contribute a PR for this?

**Comment by jack1902** [comment]
@svenwltr if i find some time and can be pointed in the right direction i will try and figure it out, i mainly know `python`, but `golang` is very readable so shouldn't be too difficult to add this feature
