### ISSUE TITLE
Provide an option to EnforceConsumerDeletion while nuking a KinesisStream

### ISSUE THREAD

**Issue by AaronLuo3296** [rebuy-de/aws-nuke#497]
While KinesisStream is trying to be nuked and a consumer is associated with it, it would fail with the following message:
`ResourceInUseException: DeleteStream can’t delete <account-id>:<data-stream-name> because there are consumers associated with this data stream. To delete <data-stream-name>  anyway, set the EnforceConsumerDeletion parameter to true to force the deletion of all the consumers that are associated with it.`
It would be nice if an option to EnforceConsumerDeletion can be provided.

**Comment by ekristen** [comment]
Closing due to age, if this is still a desired feature please open an issue at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
