### ISSUE TITLE
SNSTopic resource cannot be filtered

### ISSUE THREAD

**Issue by FlokiOo** [rebuy-de/aws-nuke#504]
Hi,

we face an issue trying to filter SNS-Topics. When I look at the code of the SNSTopic resource it expects an ID. This ID will be set as the TopicARN so I assume passing the ARN of the SNS-Topic should be the way to go. 
Unfortunately it is not working. The resource is still flagged as "would be removed". 

Any idea what could be the issue or does someone has a working example how to filter SNS-Topics?

Regards

**Comment by svenwltr** [comment]
Hello @FlokiOo.

Sorry for the late response. SNS-Topics are a bit tricky, because it has an inconvenient naming pattern for its ID. All IDs are actually prefixed with `TopicARN: `, so you have to add this to your IDs.

This is unfortunate, but we cannot change this without breaking other peoples config.

**Comment by FlokiOo** [comment]
Thx for the reply. We will give it a try.

**Comment by der-eismann** [comment]
SNS topics can now also be filtered by tags or their pure ID as properties when you pull `latest` (merged in #592).
