### ISSUE TITLE
When deleting an Aurora MySQL Database (RDS), managed snapshots fail execution

### ISSUE THREAD

**Issue by mpoitras** [rebuy-de/aws-nuke#511]
When trying to delete an Aurora database the script fails:

`eu-west-2 - NetpuneSnapshot - rds:ossk1-acdg-db72-2020-06-01-07-12 - failed
time="2020-06-01T14:09:06Z" level=error msg="There are resources in failed state, but none are ready for deletion, anymore."
time="2020-06-01T14:09:06Z" level=error msg="InvalidDBClusterSnapshotStateFault: Only manual snapshots may be deleted.\n\tstatus code: 400, request id: 62d3d9c4-5ffe-4d47-8c07-d9cf8cd26dfa"
Error: failed`

I suspect that the code runs the same for regular RDS vs Aurora. It probably try and delete snapshots managed ("owned") by amazon, and that makes it fail.

Note: the Aurora databases have been successfully deleted, and there is no snapshot that I can see, but the execution of aws-nuke stopped there.

**Comment by ekristen** [comment]
Closing due to age. Please test the fork, if this is still an issue, open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
