### ISSUE TITLE
Ability to set order of deletion

### ISSUE THREAD

**Issue by akshitkh** [rebuy-de/aws-nuke#605]
The "targets" mentioned in the "resources" section should be deleted in order. 

```
resource-types:
  # only nuke these three resources
  targets:
  - ELBv2
  - CloudFormationStack
  - SSMParameter
```

For example, aws-nuke should delete loadbalancers first, then cloudformation stacks, and then finally SSM parameters.

**Comment by polothy** [comment]
Could fix https://github.com/rebuy-de/aws-nuke/issues/629

**Comment by ekristen** [comment]
@akshitkh why would you want that order in you example?

@polothy I agree it could.

I am thinking that the tool should just learn what has to be deleted and in what order. If that tool knows that, is there really a need for a user provided order?

**Comment by ekristen** [comment]
I like this idea, but it's complicated to implement. Perhaps with the upcoming second rewrite to use AWS SDK v2 it might be possible to sneak this one in. 

This issue is tracking this feature, seeking feedback - https://github.com/ekristen/aws-nuke/issues/298

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
