### ISSUE TITLE
Infant loop waiting on VPC Endpoint resource that cannot be deleted.

### ISSUE THREAD

**Issue by james-green-affinity** [rebuy-de/aws-nuke#715]
Removal requested: 1 waiting, 30 failed, 433 skipped, 32 finished

eu-west-2 - EC2VPCEndpoint - vpce-07c5cbd1da84164bb - [tags***] - waiting

This is stuck in a loop on the CLI when I try to delete the resource in the console it says the follow:

![image](https://user-images.githubusercontent.com/91469943/144262033-f854719a-c4b3-4d09-beae-aaaf2f405395.png)

**Comment by ekristen** [comment]
Looks like a filter needs to be put in place to ignore requester-managed resources. Do you know what service you have in place that has placed the endpoint in the VPC?

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke and open an issue there if the problem persists.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
