### ISSUE TITLE
What is the Status of this Project from a Rebuy/Author Perspective

### ISSUE THREAD

**Issue by ekristen** [rebuy-de/aws-nuke#717]
Happy December 3rd Everyone.

I wanted to keep the ping minimal and so I chose only @svenwltr (highest commits) and @der-eismann (recent PR activity)

What is the status of this project ownership and contribution? I ask because I've had 3 pull requests open for 13 days now, and haven't had a single comment or feedback. There have been several issues and PRs open longer that haven't had any response from the principal team as well. There's been very little traffic on any other existing PR as far as I can tell, although today was the first day I saw a comment from @der-eismann on a recent PR opened today.

Prior to this the last commit was November 1st and last major activity was in September. 

I do realize we are in the holiday season and people are taking time off, if this is simply a by-product of that, I totally understand and appreciate the need for people to take a break, but wanted to check.

In either case, I have the following questions

- Does rebuy plan to continue to support?
- Is there plan for authors with commit access to review things on a more frequent basis?
- Are you open to bringing in others to have commit access to help curate and support? (BTW I'm volunteering)

I think there's a large need for this tool still, I have specific need for this and to expand it's capabilities. I'd like to help.

Thank you for your time.

**Comment by svenwltr** [comment]
Hello.

> What is the status of this project ownership and contribution?

We are still maintaining this, but only have time for doing this batch-wise. 

> There have been several issues [...] that haven't had any response from the principal team as well.

We do implement new resources ourselves, so these kind of issues do not get much attention from us. Other kind of issues usually should get more attention, but this also only happens batch-wise.

> Does rebuy plan to continue to support?

Yes

> Is there plan for authors with commit access to review things on a more frequent basis?

Unfortunately not. _aws-nuke_ is not near our core work, so we have to do this when we have a bit more time. Moreover merging PRs is a bit more than hitting the Merge button. We also have to make sure not to break anyone's workflow and make sure not to remove more resources than necessary. The sheer amount of services AWS is providing and the amount of new services it releases regularly does not make is easier, because we should understand the services we are supporting to some extend.

> Are you open to bringing in others to have commit access to help curate and support?

We are open to this, but this needs some kind of trust to each potential maintainer.


Thank you

**Comment by ekristen** [comment]
Thanks for the response @svenwltr.
