### ISSUE TITLE
Unable to delete EKS

### ISSUE THREAD

**Issue by Moeezulhaq** [rebuy-de/aws-nuke#814]
Hi
I am unable to delete eks resources such as Eks profile , nodegroups and cluster etc.
Can you please guide me regarding this.
![Screenshot from 2022-06-17 23-43-02](https://user-images.githubusercontent.com/81585853/174367630-de7fdfae-60e6-4e3f-93c8-1838bc65a243.png)
Thank you

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke and open an issue there if the problem persists.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
