### ISSUE TITLE
[Cloudwatch logs group] This operation, ListTagsLogGroup, has been deprecated

### ISSUE THREAD

**Issue by seifrajhi** [rebuy-de/aws-nuke#998]
Hello,

While working with aws-nuke, I was trying to delete all CloudWatch Logs log group from my dev account, but I ran into this error.
Is it normal to have it ?
This operation, ListTagsLogGroup, has been deprecated

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke, if still an issue, open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
